"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_env_variable(var_name, default=None, required=False):
    """Get environment variable or raise exception if required and not set."""
    value = os.getenv(var_name, default)
    if required and value is None:
        raise ImproperlyConfigured(f"Set the {var_name} environment variable")
    return value


def get_bool_env(var_name, default=False):
    """Get boolean environment variable."""
    value = os.getenv(var_name, str(default)).lower()
    return value in ('true', '1', 'yes', 'on')


def get_list_env(var_name, default='', separator=','):
    """Get list from environment variable."""
    value = os.getenv(var_name, default)
    return [item.strip() for item in value.split(separator) if item.strip()]


# =============================================================================
# CORE SETTINGS
# =============================================================================

# SECURITY: Secret key from environment variable
# Generate a new key: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = get_env_variable(
    'SECRET_KEY',
    default='django-insecure-dev-only-change-this-in-production',
)

# SECURITY: Debug mode - MUST be False in production
DEBUG = get_bool_env('DEBUG', False)

# Allowed hosts from environment
ALLOWED_HOSTS = get_list_env('ALLOWED_HOSTS', 'localhost,127.0.0.1')


# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_crontab',
    'celery',
    'drf_spectacular',
    # Local apps
    'authentication',
    'coreapp',
    'adminpanel',
    'ticketandcategory',
    'planandsubscription',
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'


# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be at top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.CheckUserStatus',
]

ROOT_URLCONF = 'backend.urls'


# =============================================================================
# TEMPLATES
# =============================================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =============================================================================
# DATABASE
# =============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': get_env_variable('DB_NAME', 'multinotesai'),
        'USER': get_env_variable('DB_USER', 'root'),
        'PASSWORD': get_env_variable('DB_PASSWORD', ''),
        'HOST': get_env_variable('DB_HOST', 'localhost'),
        'PORT': get_env_variable('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        'CONN_MAX_AGE': 60,  # Connection pooling
    }
}


# =============================================================================
# REST FRAMEWORK
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    'EXCEPTION_HANDLER': 'backend.exceptions.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# =============================================================================
# API DOCUMENTATION (DRF Spectacular)
# =============================================================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'MultinotesAI API',
    'DESCRIPTION': '''
## MultinotesAI - Multi-LLM SaaS Platform API

MultinotesAI is a comprehensive platform that allows users to interact with multiple
Large Language Models (LLMs) for various AI-powered tasks.

### Features
- **Multi-LLM Support**: Access multiple AI providers (TogetherAI, Gemini, OpenAI)
- **Text Generation**: Text-to-text conversations with various models
- **Image Generation**: Text-to-image generation capabilities
- **Document Analysis**: Upload and analyze documents
- **Speech-to-Text**: Audio transcription services
- **Subscription Management**: Flexible plans with token-based usage

### Authentication
All API endpoints (except public ones) require JWT Bearer token authentication.
Include the token in the Authorization header:
```
Authorization: Bearer <your_access_token>
```

### Rate Limiting
- Anonymous users: 100 requests/hour
- Authenticated users: 1000 requests/hour
    ''',
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # Authentication
    'SECURITY': [{'Bearer': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'JWT Bearer token authentication'
            }
        }
    },

    # Schema organization
    'TAGS': [
        {'name': 'Authentication', 'description': 'User registration, login, and account management'},
        {'name': 'LLM', 'description': 'Large Language Model management and selection'},
        {'name': 'Prompts', 'description': 'AI prompt submission and response management'},
        {'name': 'Folders', 'description': 'Content organization and folder management'},
        {'name': 'Documents', 'description': 'Document upload and management'},
        {'name': 'Notebooks', 'description': 'Notebook creation and management'},
        {'name': 'Subscription', 'description': 'Plan and subscription management'},
        {'name': 'Payments', 'description': 'Razorpay payment processing'},
        {'name': 'Admin', 'description': 'Administrative endpoints'},
    ],

    # Customize responses
    'POSTPROCESSING_HOOKS': [],

    # Contact information
    'CONTACT': {
        'name': 'MultinotesAI Support',
        'email': 'support@multinotesai.com',
    },

    # License
    'LICENSE': {
        'name': 'Proprietary',
    },

    # External docs
    'EXTERNAL_DOCS': {
        'description': 'MultinotesAI Documentation',
        'url': 'https://docs.multinotesai.com',
    },

    # Component settings
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
}


# =============================================================================
# JWT AUTHENTICATION
# =============================================================================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(days=7),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=30),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}


# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# =============================================================================
# STATIC & MEDIA FILES
# =============================================================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 262144000  # 250 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 262144000  # 250 MB


# =============================================================================
# CORS SETTINGS
# =============================================================================

# SECURITY: Don't allow all origins in production
CORS_ALLOW_ALL_ORIGINS = get_bool_env('CORS_ALLOW_ALL', DEBUG)

# If CORS_ALLOW_ALL_ORIGINS is False, specify allowed origins
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = get_list_env('CORS_ALLOWED_ORIGINS', 'http://localhost:5173')

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# =============================================================================
# SECURITY SETTINGS (Production)
# =============================================================================

if not DEBUG:
    # HTTPS settings
    SECURE_SSL_REDIRECT = get_bool_env('SECURE_SSL_REDIRECT', True)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # HSTS settings
    SECURE_HSTS_SECONDS = int(get_env_variable('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookie security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Additional security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

    # CSRF settings
    CSRF_TRUSTED_ORIGINS = get_list_env('CSRF_TRUSTED_ORIGINS', '')


# =============================================================================
# AWS S3 CONFIGURATION
# =============================================================================

AWS_ACCESS_KEY_ID = get_env_variable('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = get_env_variable('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = get_env_variable('AWS_BUCKET')
AWS_S3_REGION_NAME = get_env_variable('AWS_DEFAULT_REGION', 'ap-south-1')

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_QUERYSTRING_AUTH = True
AWS_QUERYSTRING_EXPIRE = 3600  # 1 hour

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = get_env_variable('SMTP_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(get_env_variable('SMTP_PORT', '587'))
EMAIL_HOST_USER = get_env_variable('SMTP_USERNAME')
EMAIL_HOST_PASSWORD = get_env_variable('SMTP_PASSWORD')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = get_env_variable('SMTP_USERNAME')


# =============================================================================
# RAZORPAY CONFIGURATION
# =============================================================================

RAZORPAY_KEY_ID = get_env_variable('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = get_env_variable('RAZORPAY_KEY_SECRET')
RAZORPAY_WEBHOOK_SECRET = get_env_variable('RAZORPAY_WEBHOOK_SECRET')


# =============================================================================
# CELERY CONFIGURATION
# =============================================================================

REDIS_URL = get_env_variable('REDIS_URL', 'redis://localhost:6379/0')

CELERY_BROKER_URL = get_env_variable('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = get_env_variable('CELERY_RESULT_BACKEND', REDIS_URL)
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes


# =============================================================================
# DJANGO CHANNELS (WebSocket)
# =============================================================================

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
        },
    },
}


# =============================================================================
# OAUTH CONFIGURATION
# =============================================================================

GOOGLE_CLIENT_ID = get_env_variable('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = get_env_variable('GOOGLE_CLIENT_SECRET')
GOOGLE_REDIRECT_URI = get_env_variable('GOOGLE_REDIRECT_URI')

FACEBOOK_APP_ID = get_env_variable('FACEBOOK_APP_ID')
FACEBOOK_APP_SECRET = get_env_variable('FACEBOOK_APP_SECRET')


# =============================================================================
# LLM API KEYS
# =============================================================================

TOGETHER_API_KEY = get_env_variable('TOGETHER_API_KEY')
GEMINI_API_KEY = get_env_variable('GEMINI_API_KEY')
OPENAI_API_KEY = get_env_variable('OPENAI_API_KEY')


# =============================================================================
# CUSTOM USER MODEL
# =============================================================================

AUTH_USER_MODEL = 'authentication.CustomUser'


# =============================================================================
# CRON JOBS
# =============================================================================

CRONJOBS = [
    ('0 0 * * *', 'authentication.cron.refreshSubscription'),  # Run daily at midnight
]


# =============================================================================
# LOGGING
# =============================================================================

LOG_LEVEL = get_env_variable('LOG_LEVEL', 'INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
(BASE_DIR / 'logs').mkdir(exist_ok=True)


# =============================================================================
# TIMEOUT SETTINGS
# =============================================================================

# Increase response timeout to 60 seconds
TIMEOUT = 60
